services:
  db:
    image: postgres:16
    container_name: store-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  backend:
    build: .
    command: >
      /entrypoint.sh
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=change_this_secret
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=storedb
    depends_on:
      - db

    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
